
package com.osisoft.xml.services.pidataservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-hudson-$BUILD_NUMBER-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PITimeSeriesService", targetNamespace = "http://xml.osisoft.com/services/PIDataService", wsdlLocation = "http://marc-web-sql.marc.net:82/PIWS2012/PITimeSeries.svc?wsdl")
public class PITimeSeriesService
    extends Service
{

    private final static URL PITIMESERIESSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.osisoft.xml.services.pidataservice.PITimeSeriesService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.osisoft.xml.services.pidataservice.PITimeSeriesService.class.getResource(".");
            url = new URL(baseUrl, "http://marc-web-sql.marc.net:82/PIWS2012/PITimeSeries.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://marc-web-sql.marc.net:82/PIWS2012/PITimeSeries.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PITIMESERIESSERVICE_WSDL_LOCATION = url;
    }

    public PITimeSeriesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PITimeSeriesService() {
        super(PITIMESERIESSERVICE_WSDL_LOCATION, new QName("http://xml.osisoft.com/services/PIDataService", "PITimeSeriesService"));
    }

    /**
     * 
     * @return
     *     returns IPITimeSeries
     */
    @WebEndpoint(name = "BasicEndpoint")
    public IPITimeSeries getBasicEndpoint() {
        return super.getPort(new QName("http://xml.osisoft.com/services/PIDataService", "BasicEndpoint"), IPITimeSeries.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPITimeSeries
     */
    @WebEndpoint(name = "BasicEndpoint")
    public IPITimeSeries getBasicEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://xml.osisoft.com/services/PIDataService", "BasicEndpoint"), IPITimeSeries.class, features);
    }

}
